### ISSUE TITLE
Publishing Build Info to Projects Using the Maven Artifactory Plugin

### ISSUE THREAD

**Issue by samrjfrog** [jfrog/artifactory-maven-plugin#25] opened 2021-11-14 17:15 UTC
We would like the ability to publish the build information from a Maven build to a specific project in Artifactory (as opposed to the general artifactory-build-info location) via the Artifactory Maven Plugin or customizable pom parameter.

Currently the only way to implement this is via the JFrog CLI which would greatly complicate our builds.

**Comment by jghal** [comment] 2021-12-06 19:01
Is this duplicate of #21?

**Comment by sverdlov93** [comment] 2022-02-14 15:56
Hi @samrjfrog,
artifactory-maven-plugin 3.4.0 is released and contains support for Artifactory Projects.
Looking forward to your feedback on it.

**Closed** 2022-02-16 09:14 UTC
Labels: feature request
